### ISSUE TITLE
Excel export with object list datasource

### ISSUE THREAD

**Issue by MartinPerrie** [OpenNTF/POI4Xpages#31]
Hi Christian
I installed the latest build 1.3.0.201412302058 and did a rebuild on the POI Example database. When attempting an export from "View with object list datasource" I'm getting : 
HTTP JVM: SEVERE: Error on getValue() (biz.webgate.dominoext.poi.component.sources.ListObjectDataSource)

and the following in error-log-0.xml

    <values>biz.webgate.dominoext.poi.utils.exceptions.POIException: Error during computeValue:Error while executing JavaScript action expression
at biz.webgate.dominoext.poi.component.data.AbstractDefinition.executeComputeValue(AbstractDefinition.java:80)
at biz.webgate.dominoext.poi.component.sources.ListObjectDataSource.getValue(ListObjectDataSource.java:107)
at biz.webgate.dominoext.poi.component.kernel.workbook.EmbeddedDataSourceExportProcessor.processExportRow(EmbeddedDataSourceExportProcessor.java:60)
at biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor.processSpreadSheet(WorkbookProcessor.java:248)
at biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor.processWorkbook(WorkbookProcessor.java:196)
at biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor.generateNewFile(WorkbookProcessor.java:150)
at biz.webgate.dominoext.poi.component.containers.UIWorkbook.processAjaxRequest(UIWorkbook.java:177)
at biz.webgate.dominoext.poi.component.actions.WorkbookGenerationServerAction.invoke(WorkbookGenerationServerAction.java:48)
at com.ibm.xsp.application.ActionListenerImpl.processAction(ActionListenerImpl.java:60)
at javax.faces.component.UICommand.broadcast(UICommand.java:324)
at com.ibm.xsp.component.UIEventHandler.broadcast(UIEventHandler.java:366)
at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
at com.ibm.xsp.extlib.component.layout.UIVarPublisherBase.broadcast(UIVarPublisherBase.java:183)
at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
at com.ibm.xsp.component.UIViewRootEx.broadcast(UIViewRootEx.java:1535)
at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:307)
at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:428)
at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:94)
at com.sun.faces.lifecycle.LifecycleImpl.phase(LifecycleImpl.java:210)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:96)
at com.ibm.xsp.controller.FacesControllerImpl.execute(FacesControllerImpl.java:256)
at com.ibm.xsp.webapp.FacesServlet.serviceView(FacesServlet.java:228)
at com.ibm.xsp.webapp.FacesServletEx.serviceView(FacesServletEx.java:157)
at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:160)
at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)
at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:576)
at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1335)
at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:853)
at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:796)
at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:565)
at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1319)
at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:662)
at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:482)
at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:350)
at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:306)
at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Caused by: com.ibm.xsp.exception.EvaluationExceptionEx: Error while executing JavaScript action expression
at com.ibm.xsp.binding.javascript.JavaScriptMethodBinding.invoke(JavaScriptMethodBinding.java:126)
at biz.webgate.dominoext.poi.component.data.AbstractDefinition.executeComputeValue(AbstractDefinition.java:75)
... 36 more
Caused by: com.ibm.jscript.InterpretException: Script interpreter error, line=1, col=5: Unknown member 'getDocument' in Java class 'biz.webgate.domino.poi.demodb.contact.Contact';
at com.ibm.jscript.types.JavaAccessObject.get(JavaAccessObject.java:772)
at com.ibm.jscript.types.FBSReferenceByName.getValue(FBSReferenceByName.java:93)
at com.ibm.jscript.ASTTree.InterpretResult.getFBSValue(InterpretResult.java:70)
at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:91)
at com.ibm.jscript.ASTTree.ASTMember.interpret(ASTMember.java:106)
at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:88)
at com.ibm.jscript.ASTTree.ASTProgram.interpret(ASTProgram.java:119)
at com.ibm.jscript.ASTTree.ASTProgram.interpretEx(ASTProgram.java:139)
at com.ibm.jscript.JSExpression._interpretExpression(JSExpression.java:435)
at com.ibm.jscript.JSExpression.access$1(JSExpression.java:424)
at com.ibm.jscript.JSExpression$2.run(JSExpression.java:414)
at java.security.AccessController.doPrivileged(AccessController.java:362)
at com.ibm.jscript.JSExpression.interpretExpression(JSExpression.java:410)
at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:251)
at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:234)
at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:222)
at com.ibm.xsp.binding.javascript.JavaScriptMethodBinding.invoke(JavaScriptMethodBinding.java:111)
... 37 more
</values>

**Comment by guedeWebGate** [comment]
Hi Martin
This is an Error in the Example DB. I will include the building of the example DB also in the code drop. Only the maven plugin for the headless designer must be part of maven.central, but we are a step away of this.
