### ISSUE TITLE
Problem with Generate Workbook

### ISSUE THREAD

**Issue by xpauser** [OpenNTF/POI4Xpages#45]
When attempting an export from "List Object Datasource", sometimes this error occurs.
It's not always but it will work well after several times retry.
I hope the problem will be solved.

java.lang.IllegalStateException: The page can not use a PrintWriter when it's already opened a ServletOutputStream.
	at com.ibm.domino.xsp.bridge.http.servlet.XspCmdHttpServletResponse.getWriter(XspCmdHttpServletResponse.java:171)
	at com.ibm.designer.runtime.domino.adapter.servlet.LCDAdapterHttpServletResponse.getWriter(LCDAdapterHttpServletResponse.java:193)
	at biz.webgate.dominoext.poi.utils.logging.ErrorPageBuilder.processError(ErrorPageBuilder.java:28)
	at biz.webgate.dominoext.poi.component.kernel.WorkbookProcessor.generateNewFile(WorkbookProcessor.java:95)
	at biz.webgate.dominoext.poi.component.containers.UIWorkbook.processAjaxRequest(UIWorkbook.java:177)
	at biz.webgate.dominoext.poi.component.actions.WorkbookGenerationServerAction.invoke(WorkbookGenerationServerAction.java:48)
	at com.ibm.xsp.actions.ActionGroup.invoke(ActionGroup.java:135)
	at com.ibm.xsp.application.ActionListenerImpl.processAction(ActionListenerImpl.java:60)
	at javax.faces.component.UICommand.broadcast(UICommand.java:324)
	at com.ibm.xsp.component.UIEventHandler.broadcast(UIEventHandler.java:366)
	at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
	at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
	at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
	at com.ibm.xsp.extlib.component.layout.UIVarPublisherBase.broadcast(UIVarPublisherBase.java:183)
	at com.ibm.xsp.component.UIDataPanelBase.broadcast(UIDataPanelBase.java:400)
	at com.ibm.xsp.component.UIViewRootEx.broadcast(UIViewRootEx.java:1535)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:307)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:428)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:94)
	at com.sun.faces.lifecycle.LifecycleImpl.phase(LifecycleImpl.java:210)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:96)
	at com.ibm.xsp.controller.FacesControllerImpl.execute(FacesControllerImpl.java:256)
	at com.ibm.xsp.webapp.FacesServlet.serviceView(FacesServlet.java:227)
	at com.ibm.xsp.webapp.FacesServletEx.serviceView(FacesServletEx.java:157)
	at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:159)
	at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)
	at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:588)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1335)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:865)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:808)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:577)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1319)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:662)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:482)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)

---
POI4XPages_1_3_1

Lotus Domino Server 9.0.1 FP9 64 bit
OS：Windows 2012 Server R2 Standard 64bit

IBM Domino Designer 9.0
Social Edition 9.0.1FP8 
Revision 20170228.0813-FP8 (Release 9.0.1FP8) 
Standard Edition L-GHUS-968PRV

**Comment by xpauser** [comment]
The POI 4 XPages action "Generate Workbook" is set as a simple action in an onClick event of a button.
I found [this](https://stackoverflow.com/questions/19668888/java-exception-cant-get-a-writer-while-an-outputstream-is-already-in-use-whe) information.
So, I tried to add a simple action including "facesContext.responseComplete();" as a script code after the above action.
But the problem wasn't solved.
It might as well be written in the source code.
Thinking in a different way, I tried using XAgent with the "Generate Workbook" action.
The problem was settled.
